version: "3.8"

services:
  sqlserver_db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuPasswordSegura"  # use the same as in Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data   # mount your data folder to the container
    restart: unless-stopped